### PR TITLE
BR 4.7.1

### PR DESCRIPTION
**Pull request by iisa**
https://github.com/internetarchive/bookreader/releases/new?tag=v4.7.1&title=v4.7.1&body=-%20Add%20new%20parameters%20to%20analytics%20%40bfalling%0A

### CODE REVIEW

**Comment by jbuckner** [comment]
Did something change in this MR? There's no code changes, but the compiled Bookreader.js file changed.

**Comment by iisa** [comment]
> Did something change in this MR? There's no code changes, but the compiled Bookreader.js file changed.

You know, I asked myself the same thing so I checked the last tag release, and it does the same thing: https://github.com/internetarchive/bookreader/pull/278/files

**Comment by jbuckner** [comment]
Oh I see. So was the actual code change in a different MR?

**Comment by jbuckner** [comment]
Nvm I found it.

**Pull request merged**
