### PR TITLE
Add two-way iframe communication via postMessage to URL Plugin

### PR DESCRIPTION
**Pull request by evanminto**
Also adds some QUnit tests and updates documentation.

Jira: WEBDEV-1528

### CODE REVIEW

**Comment by rchrd2** [comment]
In package.json there's a script for "node-qunit-phantomjs", but it's not included as a dep. Can you please add `node-qunit-phantomjs` to package.json or remove the script if it's not used.

**Comment by evanminto** [comment]
My thinking on the iframe communication being its own plugin: I considered it, but it’s kind of tied to the idea of the params path and the URL. I don't see a way that it could be decoupled from that, but maybe I'm missing something.

**Comment by evanminto** [comment]
I should say, it's not IMPOSSIBLE to decouple it, but it would require a bigger rethink of the interface that plugins and other code use to interact with BookReader (i.e. more based on events and less on prototype modification).

**Comment by rchrd2** [comment]
But what if it was a plugin that depends on the url plugin? In the comment it could say "depends on plugin.url.js".

**Comment by evanminto** [comment]
I'm not comfortable with having plugin dependencies like that, at least not right now while the plugins are all tightly coupled to the internal workings of BookReader. You'd have one plugin which makes prototype modifications and relies on prototype modifications made by another plugin. Gets pretty gnarly if you ever want to, say, change the URL plugin.

**Comment by rchrd2** [comment]
The unfortunately fact is, plugins already have some dependencies. Each is
not 100% isolated.

**Comment by evanminto** [comment]
This is ready for re-review, @rchrd2.

**Pull request merged**
