### PR TITLE
435/fix/testcafe flaky

### LINKED ISSUE #435: Testcafe tests failing frequently, but inconsistently
Master build failing; seems to have gotten flakier after #367

### PR DESCRIPTION
**Pull request by cdrini**
Closes #435

~Mainly just some misc clean ups trying to reduce how often its failing :( It seems to have helped! I also disabled travis for branches (now only runs on PRs), so I think that might've helped as well.~

What fixed it was enabling testcafe quarantine mode. This will basically rerun upto thrice.

I'd recommend viewing commit-by-commit; each is very single-purpose.

### CODE REVIEW

**Comment by cdrini** [comment]
Passed once! Running again... (Note since this is a fork branch, it only runs the PR step, and not the branch step)

**Comment by cdrini** [comment]
Passed twice! Once more for good luck... 🤞

**Comment by cdrini** [comment]
Timedout, but _didn't fail_! So still good; let me try it again.

**Comment by cdrini** [comment]
It failed :( Let me try enabling "quarantine mode" 😐

**Comment by cdrini** [comment]
Passing once!

**Comment by cdrini** [comment]
Passing twice...! 🤞

**Comment by cdrini** [comment]
Passing thrice 🎉 ! Calling it ready for review :P

**Review by bfalling — APPROVED** [review]
LGTM

**Comment by cdrini** [comment]
Thanks @bfalling !

**Pull request merged**
