### PR TITLE
Enable eslint, and do some cleanup

### PR DESCRIPTION
**Pull request by nikolas**
Hi,
So do with this what you want. I just noticed the bookreader doesn't
have eslint set up. This gets BookReader.js passing under eslint.
I've also added a travis.yml file if you want to have travis
automatically check that.

### CODE REVIEW

**Comment by rchrd2** [comment]
Thanks for this. I have some refactors I am working on in another branch.  
I need to find a path to least merge conflicts, and then I'll merge this.

**Comment by rchrd2** [comment]
Is it possible for you to rebase or remove the changes you did to BookReader.js?

This PR came at the same time a significant refactor was being done in another branch. It's merged into master now.

**Comment by nikolas** [comment]
Yeah, I can rebase, no problem.

**Comment by nikolas** [comment]
It will be more straightforward to just re-apply eslint to the new BookReader.js rather than wading through this merge conflict, so I'll do that now and let you know when that's done.

**Comment by rchrd2** [comment]
Great. Thanks again for this. Merging now.

**Pull request merged**
