### PR TITLE
Issue #445 Added new rule 

### LINKED ISSUE #445: Add "space-after-keywords" always eslint + fix violators
Eslint docs: https://eslint.org/docs/rules/space-after-keywords

### Summary of Requirements
- [ ] New rule added to eslint rc
- [ ] `npm run lint:fix` used to fix any violators

### Stakeholders

### PR DESCRIPTION
**Pull request by Yashs911**
Fixes #445

### CODE REVIEW

**Comment by cdrini** [comment]
Hi @Yashs911 ! Looking good :) Please rebase off latest master, and also don't commit the change to the package*.json files.

**Comment by Yashs911** [comment]
Hi, @cdrini While updating my master branch it is showing that there is a merge conflict. So how to resolve that.
and I have made the changes in a separate branch so how to rebase it to my master? "git rebase master"?
P.S. I am new to open source

**Comment by cdrini** [comment]
Hi @Yashs911 ; you might want to take a look at https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet if you're new to git :) If you're new to git, I'd recommend creating a fresh branch following the instructions there, and not `git add`-ing the files in question. Hope that helps!

**Comment by Yashs911** [comment]
Hi, @cdrini I have created a new PR. Sorry if I caused any inconvenience.

**Pull request closed without merging**
