### PR TITLE
WIP: Added query parameter q for fts inside book

### PR DESCRIPTION
**Pull request by nsharma123**
This PR is based on https://webarchive.jira.com/browse/WEBDEV-3104

### CODE REVIEW

**Comment by nsharma123** [comment]
@cdrini please have a look on JIRA comments here https://webarchive.jira.com/browse/WEBDEV-3104. These changes are already on this review app. Thanks!

**Comment by cdrini** [comment]
Ah, ok, thanks! It looks like these issues are observable:

- ❌ Stream endpoint does not start a search; e.g. https://58-review-developeme-51mtnb.archive.org/stream/goody#mode/2up?q=hello
- ❌ Removes any existing url parameters
    1. Go to https://58-review-developeme-51mtnb.archive.org/details/goody/mode/2up?admin=1
    2. Search for something with the UI
    3. `admin` removed from url

**Comment by mc2** [comment]
http://localhost:8000/BookReaderDemo/demo-ia-plato.html#page/254/mode/2up/search/knowledge?admin=1

is changed to:

http://localhost:8000/BookReaderDemo/demo-ia-plato.html#page/254/mode/2up?q=knowledge?admin=1

and the search is for `knowledge?admin=1`

**Comment by mc2** [comment]
This has been superseded by merged https://github.com/internetarchive/bookreader/pull/321

**Pull request closed without merging**
