### PR TITLE
Removed menu tab at the bottom right

### LINKED ISSUE #487: Remove menu tab at the bottom right
- Remove menu tab at bottom right of screen, just above the 'fullscreen' button
image

Acceptance: 
- dom element is removed
- css for that button is removed

When PR:
- add a gif to show that on-page-load, the tab is no longer present

### PR DESCRIPTION
**Pull request by Yashs911**
Fixes #487

### CODE REVIEW

**Comment by Yashs911** [comment]
@iisa Please review this PR

**Comment by Yashs911** [comment]
@cdrini  Can you please review this PR and sorry if I caused any inconvenience.

**Comment by iisa** [comment]
looks good - horizontal nav functionality has not been affected.

Thanks so much for making this happen!
image

**Review by iisa — APPROVED** [review]
LGTM

**Review by jeeva2812 — APPROVED** [review]
LGTM! Thanks for your contribution.

**Pull request merged**
