### PR TITLE
Fix search results not positioned correctly Mode1Up

### PR DESCRIPTION
**Pull request by cdrini**
They need to take into account PPI now!

### CODE REVIEW

**Review by dualcnhq — APPROVED** [review]

**Comment by dualcnhq** [comment]
Testing steps:

bookreader-search-mode

**Comment by giancarlobi** [comment]
@cdrini Thanks! I was debugging a couple of days to found how to solve that and finally I found an analog solution overriding  updateSearchHilites1UP whit this code (FYI):
``` js

      const pagePPI = this.getPageProp(pageIndex, 'ppi', this.options.ppi);
...
        if ('mode1Up' in this._modes) {

          //To make highlight mode1Up working
          //We have to use reduceBoxFactor as calculated below instead of this.reduce
          const reduceBoxFactor = (pagePPI / this._modes.mode1Up.screenDPI * this._modes.mode1Up.realWorldReduce);
          const highlight = {
            width:  `${(box.r - box.l) / reduceBoxFactor}px`,
            height: `${(box.b - box.t) / reduceBoxFactor}px`,
            left:   `${(box.l) / reduceBoxFactor}px`,
            top:    `${(box.t) / reduceBoxFactor}px`
          };
          $(box.div).css(highlight);

        } else {

          const highlight = {
            width:  `${(box.r - box.l) / this.reduce}px`,
            height: `${(box.b - box.t) / this.reduce}px`,
            left:   `${(box.l) / this.reduce}px`,
            top:    `${(box.t) / this.reduce}px`
          };
          $(box.div).css(highlight);

        }

```
Probably your code is a better solution for this.
FYI I added a check to make code backward compatible with IAB v. 4.21.0 (the current we are using but we want switch to the last one 4.40.2).
Thanks again.

**Comment by cdrini** [comment]
Good sleuthing, @giancarlobi ! That's essentially exactly my fix; I'm just using a few more method calls :)

Hmmm, out of curiosity, how are you using BookReader? Having the search plugins from v4.40.2 with BookReader core at 4.21.0 might cause some unexpected issues 😅

**Comment by giancarlobi** [comment]
> Hmmm, out of curiosity, how are you using BookReader? Having the search plugin from v4.40.2 with BookReader core at 4.21.0 might cause some unexpected issues sweat_smile

@cdrini You are right, I didn't have well explained.  We have our code (see https://github.com/esmero/format_strawberryfield) around IAB so I was thinking in our code compatible with both IAB version.
This was waiting your new release but you was so fast and I saw 4.40.3 is out (few minutes ago) and this allows us a single update to IAB 4.40.3 without need to override.
Thanks !!!!!

**Comment by cdrini** [comment]
Ahhh, I understand. What a very cool project! Thank you for sharing :) Let us know if you have any issues with the upgrade, and we'll be able to help fix anything on our end that might help! Cheers!

**Comment by giancarlobi** [comment]
@cdrini Thanks twice! I upgraded to 4.40.3 and all seems work fine. 
I'd like to show you a feature I implemented a couple of years ago on our IAB deployment: ZOOM based on openseadragon .
If you browse here https://archipelago.byterfly.eu/do/0a1cc2b9-142b-493e-b0a9-7996dca827da#page/16/mode/2up and click on ZOOM (up right corner) you'll see openseadragon opening pages.
That is working also with previous IAB release as this one https://www.byterfly.eu/islandora/object/libria:103213#page/234/mode/2up, just FYI.

**Comment by giancarlobi** [comment]
@cdrini FYI you can see here https://github.com/esmero/format_strawberryfield/blob/88749eece18afdb14a1071385a7b1615f4980dab/js/iiif-iabookreader_strawberry.js#L78 the main code for that feature. just in case

**Comment by cdrini** [comment]
@giancarlobi We've been working on adding something like that native to bookreader :) After a lot of work, it's now ready for some QA! Here's the PR: https://github.com/internetarchive/bookreader/pull/806 ; and here's where you can try it: https://deploy-preview-806--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala . It doesn't do tiling like openseadragon does, but it does support smooth zoom using trackpad or touchscreen.

**Comment by giancarlobi** [comment]
@cdrini Great! I'm on holidays and I'll check it next week. Thanks!

**Comment by cdrini** [comment]
Haha, I'll be on holiday next week :P But this will be in QA until I'm back the week after.

**Pull request merged**
